---
- name: Deploy a webserver and a webapp
  hosts: web
  gather_facts: false
  become: true

  tasks:
    - name: Install the apache web server
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Open the http service for the web server on the firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Enable and start the apache webserver
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Copy the files from the files directory to /var/www/html
      ansible.builtin.copy:
        src: files/web/
        dest: /var/www/html/
        mode: '0755'
        owner: root
        group: root
        setype: httpd_sys_content_t

- name: Smoke test for the webservers
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Is website reachable
      ansible.builtin.uri:
        url: "http://{{ item }}/"
        return_content: true
        method: GET
        status_code:
          - 200
      register: smoke_test
      loop: "{{ groups['web'] }}"

    - name: Is content right
      ansible.builtin.fail:
        msg: Hello should be part of the website text at {{ item['url'] }}
      when: "('Hellox' | lower )
        not in 
        (item['content'] | lower)"
      loop: "{{ smoke_test['results'] }}"

